{{- if and (eq .Values.idm.enabled true) (eq .Values.idm.bundidIdp.enabled true) }}
{{/* Allows the Mesh incoming requests to access BundID-IDP in the IDM Namespace */}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: bundid-idp-allow-access-from-ingress
  labels:
    component: idm
spec:
  selector:
    matchLabels:
      app: bundid-idp
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [
              "cluster.local/ns/istio-system/sa/istio-ingressgateway"
            ]
      to:
        - operation:
            methods: [ "GET", "POST", "PUT" ]
            paths: [
              "/*"
            ]
{{- end }}
