{{- if and (eq .Values.idm.enabled true) (eq .Values.tcp.principals.enabled false) }}
{{/* Allows the Cluster Services to access Redis in the IDM Namespace */}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: redis-cus-allow-access-from-all
  labels:
    component: idm
spec:
  selector:
    matchLabels:
      app: redis-cus
  action: ALLOW
  rules:
  - from:
    - source:
        ipBlocks: ["0.0.0.0/0"]
    to:
    - operation:
        # TCP Only
        ports: ["6379"]
{{- end }}
