{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ars-allow-access-from-ingress
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: ars-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/istio-system/sa/istio-ingressgateway",
        ]
    to:
    - operation:
        methods: [ "POST" ]
        {{- if eq .Values.featureFlags.newApiEndpoints true }}
        paths: [
          "/$process-notification",
          "/%24process-notification"
        ]
        {{- else }}
        paths: [
          "/fhir/$process-notification",
          "/fhir/%24process-notification"
        ]
        {{- end }}
    when:
      - key: request.auth.claims[realm_access][roles]
        values: [ "ars-data-sender" ]
{{- end }}
