{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ces-allow-access-from-internal
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: context-enrichment-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/{{ .Release.Namespace }}/sa/report-processing-service*",
          "cluster.local/ns/{{ .Release.Namespace }}/sa/notification-processing-service*",
          "cluster.local/ns/{{ .Release.Namespace }}/sa/igs-service*",
          "cluster.local/ns/{{ .Release.Namespace }}/sa/ars-service*"
        ]
    to:
      - operation:
          methods: [ "POST" ]
          paths: [
            "/enrichment"
          ]
{{- end }}