{{- if and (eq .Values.demis.enabled true ) (eq .Values.demis.dls.enabled true) }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: dls-reader-allow-access-from-ingress
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: destination-lookup-reader
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/istio-system/sa/istio-ingressgateway"
        ]
    to:
    - operation:
        methods: ["GET"]
        paths:
         - "/notification*"
    when:
      - key: request.auth.claims[realm_access][roles]
        values:
          - "disease-notification-sender"
          - "pathogen-notification-sender"

{{- end }}
