{{- if and (eq .Values.demis.enabled true ) (eq .Values.demis.dls.enabled true)  }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: dls-reader-allow-access-from-internal
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: destination-lookup-reader
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/{{ .Release.Namespace }}/sa/notification-processing-service*",
          "cluster.local/ns/{{ .Release.Namespace }}/sa/notification-routing-service*"
        ]
    to:
    - operation:
        methods: ["GET"]
        paths:
          - "/notification*"
{{- end }}
