{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: futs-igs-allow-access-from-internal
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: futs-igs
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [
              "cluster.local/ns/{{ .Release.Namespace }}/sa/gateway-igs*"
            ]
      to:
        - operation:
            methods: [ "GET" ]
            paths: [ "/ValueSet" ]
{{- end }}