{{- if and (eq .Values.demis.enabled true) (has "gateway-igs" .Values.demis.gateway.services) }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: gateway-igs-allow-access-from-internal
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: gateway-igs
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [
            "cluster.local/ns/istio-system/sa/istio-ingressgateway",
            "cluster.local/ns/{{ .Release.Namespace }}/sa/igs-service*"
            ]
      to:
        - operation:
            methods: ["POST"]
            paths: [
              "/notification-sequence/$process-notification-sequence",
              "/notification-sequence/%24process-notification-sequence",
              "/document-reference",
              "/csv/upload"
            ]
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "igs-sequence-data-sender", "igs-notification-data-sender", "igs-sequence-data-sender-fasta-only" ]
    {{/* Allow all operations for the given IPs */}}
    {{- (include "policies-authorization-chart.allow_all_operations_for_ips" .) | indent 4 }}
{{- end }}