{{- if and (eq .Values.demis.enabled true) (has "gateway-pathogen" .Values.demis.gateway.services) }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: gateway-pathogen-allow-access-from-ingress
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: gateway-pathogen
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-system/sa/istio-ingressgateway" ]
      to:
        - operation:
            methods: [ "POST" ]
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
            paths: [ "/notification/pathogen" ]
            {{- else }}
            paths: [ "/api/ng/notification/pathogen" ]
            {{- end }}
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "pathogen-notification-sender" ]
    {{/* Allow all operations for the given IPs */}}
    {{- (include "policies-authorization-chart.allow_all_operations_for_ips" .) | indent 4 }}
{{- end }}