{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: hls-allow-from-ingress
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: hospital-location-service
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [
              "cluster.local/ns/istio-system/sa/istio-ingressgateway"
            ]
      to:
        - operation:
            methods: [ "GET" ]
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
            paths: [ "/locations" ]
            {{- else }}
            paths: [ "/hospital-locations" ]
            {{- end }}
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "bed-occupancy-sender" ]
    {{/* Allow all operations for the given IPs */}}
    {{- (include "policies-authorization-chart.allow_all_operations_for_ips" .) | indent 4 }}
{{- end }}