{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: lvs-allow-access-from-internal
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: lifecycle-validation-service
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/{{ .Release.Namespace }}/sa/notification-processing-service*"
        ] 
    to:
    - operation:
        methods: ["POST"] 
        paths: ["/laboratory/*", "/disease/*"]
{{- end }}