{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: notification-gw-allow-access-from-ingress
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: notification-gateway
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-system/sa/istio-ingressgateway" ]
      to:
        - operation:
            methods: [ "POST" ]
            paths:
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
              - "/reports/bedOccupancy"
            {{- end }}
              - "/api/ng/reports/bedOccupancy"
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "bed-occupancy-sender" ]
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-system/sa/istio-ingressgateway" ]
      to:
        - operation:
            methods: [ "POST" ]
            paths:
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
              - "/notification/disease"
            {{- end }}
              - "/api/ng/notification/disease"
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ 
            "disease-notification-sender"
          ]
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-system/sa/istio-ingressgateway" ]
      to:
        - operation:
            methods: [ "POST" ]
            paths:
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
              - "/notification/disease/7.3/anonymous"
            {{- end }}
              - "/api/ng/notification/disease/7.3/anonymous"
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ 
            "disease-notification-anonymous-sender"
          ]
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-system/sa/istio-ingressgateway" ]
      to:
        - operation:
            methods: [ "POST" ]
            paths:
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
              - "/notification/disease/7.3/non_nominal"
            {{- end }}
              - "/api/ng/notification/disease/7.3/non_nominal"
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ 
            "disease-notification-nonnominal-sender"
          ]
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-system/sa/istio-ingressgateway" ]
      to:
        - operation:
            methods: [ "POST" ]
            paths:
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
              - "/notification/pathogen"
              - "/notification/pathogen/7.1"
            {{- end }}
              - "/api/ng/notification/pathogen"
              - "/api/ng/notification/pathogen/7.1"
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "pathogen-notification-sender"]
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-system/sa/istio-ingressgateway" ]
      to:
        - operation:
            methods: [ "POST" ]
            paths:
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
              - "/notification/pathogen/7.3/non_nominal"
            {{- end }}
              - "/api/ng/notification/pathogen/7.3/non_nominal"
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "pathogen-notification-nonnominal-sender" ]
    - from:
        - source:
            principals: [ "cluster.local/ns/istio-system/sa/istio-ingressgateway" ]
      to:
        - operation:
            methods: [ "POST" ]
            paths:
            {{- if eq .Values.featureFlags.newApiEndpoints true }}
              - "/notification/pathogen/7.3/anonymous"
            {{- end }}
              - "/api/ng/notification/pathogen/7.3/anonymous"
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ "pathogen-notification-anonymous-sender" ]
    {{/* Allow all operations for the given IPs */}}
    {{- (include "policies-authorization-chart.allow_all_operations_for_ips" .) | indent 4 }}
{{- end }}
