{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: nps-allow-access-from-ingress
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: notification-processing-service
  action: ALLOW
  rules:
    - from:
      - source:
          principals: 
            - "cluster.local/ns/istio-system/sa/istio-ingressgateway"
            {{- include "policies-authorization-chart.gateway_service_accounts" (dict "namespace" .Release.Namespace "services" .Values.demis.gateway.services) | indent 12}}
      to:
      - operation:
          methods: ["POST"]
          {{- if eq .Values.featureFlags.newApiEndpoints true }}
          paths: [
            "/$process-notification",
            "/%24process-notification"
          ]
          {{- else }}
          paths: [
            "/fhir/$process-notification",
            "/fhir/%24process-notification"
          ]
          {{- end }}
      when:
        - key: request.auth.claims[realm_access][roles]
          values: [ 
            "disease-notification-sender", 
            "disease-notification-nonnominal-sender" ,
            "disease-notification-anonymous-sender",
            "pathogen-notification-sender",
            "pathogen-notification-nonnominal-sender",
            "pathogen-notification-anonymous-sender",
            "pathogen-notification-negative-sender"
           ]
    {{/* Allow all operations for the given IPs */}}
    {{- (include "policies-authorization-chart.allow_all_operations_for_ips" .) | indent 4 }}
{{- end }}