{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: vs-ars-allow-access-from-internal
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: validation-service-ars
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/{{ .Release.Namespace }}/sa/ars-service*",
        ]
    to:
    - operation:
        methods: ["POST"]
        paths: []
{{- end }}
