{{- if eq .Values.demis.enabled true }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: vs-core-allow-access-from-internal
  labels:
    component: demis
spec:
  selector:
    matchLabels:
      app: validation-service-core
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
          "cluster.local/ns/{{ .Release.Namespace }}/sa/notification-processing-service*",
          "cluster.local/ns/{{ .Release.Namespace }}/sa/report-processing-service*"
        ] 
    to:
    - operation:
        methods: ["POST"] 
        paths: []
{{- end }}