{{- if and (eq .Values.postgres.enabled true) (eq .Values.tcp.principals.enabled true)}}
{{/* Allows the Cluster Services to access PostgreSQL */}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: postgres-allow-access-from-internal
  labels:
    component: database
spec:
  selector:
    matchLabels:
      app: postgres
  action: ALLOW
  rules:
  - from:
    - source:
        principals: [
            "cluster.local/ns/{{ .Release.Namespace }}/sa/pgbouncer*"
          ]
    to:
    - operation:
        # TCP Only
        ports: ["5432"]
{{- end }}
